In [2]:
# import packages
from sklearn import datasets
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
# import data
df=datasets.load_breast_cancer()

In [5]:
# view data
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [6]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
df.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
# data preparation
X=df.data
y=df.target

In [9]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [12]:
print(X_train.shape,X_test.shape)

(455, 30) (114, 30)


In [13]:
# build neural network
model=tf.keras.models.Sequential()

In [15]:
model.add(tf.keras.layers.Dense(units=15, activation='relu', kernel_initializer='uniform', input_dim=30))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [16]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                465       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 16        
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
455/455 [==============================] - 0s 356us/sample - loss: 0.6367 - binary_accuracy: 0.9231
Epoch 2/100
455/455 [==============================] - 0s 80us/sample - loss: 0.4307 - binary_accuracy: 0.9341
Epoch 3/100
455/455 [==============================] - 0s 93us/sample - loss: 0.2582 - binary_accuracy: 0.9385
Epoch 4/100
455/455 [==============================] - 0s 79us/sample - loss: 0.1807 - binary_accuracy: 0.9560
Epoch 5/100
455/455 [==============================] - 0s 91us/sample - loss: 0.1426 - binary_accuracy: 0.9648
Epoch 6/100
455/455 [==============================] - 0s 88us/sample - loss: 0.1201 - binary_accuracy: 0.9736
Epoch 7/100
455/455 [==============================] - 0s 85us/sample - loss: 0.1049 - binary_accuracy: 0.9758
Epoch 8/100
455/455 [==============================] - 0s 75us/sample - loss: 0.0945 - binary_accuracy: 0.9780
Epoch 9/100
455/455 [==============================] - 0s 82us/sample - loss: 0.0870 - binary_accuracy: 0.9780


455/455 [==============================] - 0s 77us/sample - loss: 0.0261 - binary_accuracy: 0.9934
Epoch 74/100
455/455 [==============================] - 0s 77us/sample - loss: 0.0257 - binary_accuracy: 0.9934
Epoch 75/100
455/455 [==============================] - 0s 70us/sample - loss: 0.0250 - binary_accuracy: 0.9934
Epoch 76/100
455/455 [==============================] - 0s 72us/sample - loss: 0.0249 - binary_accuracy: 0.9934
Epoch 77/100
455/455 [==============================] - 0s 75us/sample - loss: 0.0243 - binary_accuracy: 0.9934
Epoch 78/100
455/455 [==============================] - 0s 79us/sample - loss: 0.0244 - binary_accuracy: 0.9934
Epoch 79/100
455/455 [==============================] - 0s 83us/sample - loss: 0.0234 - binary_accuracy: 0.9934
Epoch 80/100
455/455 [==============================] - 0s 72us/sample - loss: 0.0230 - binary_accuracy: 0.9934
Epoch 81/100
455/455 [==============================] - 0s 79us/sample - loss: 0.0230 - binary_accuracy: 0.9934
Epoch

In [21]:
test_loss,test_accuracy=model.evaluate(X_test,y_test)
print(f'Test loss {test_loss} and test accuracy {test_accuracy}')

114/114 [==============================] - 0s 219us/sample - loss: 0.0565 - binary_accuracy: 0.9912
Test loss 0.05647204001025673 and test accuracy 0.9912280440330505
